version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt

      - run:
          name: Run tests
          command: |
            pytest

      - persist_to_workspace:
          root: /app
          paths:
            - .

  build_and_push_docker:
    docker:
      - image: docker:stable

    steps:
      - attach_workspace:
          at: /app

      - run:
          name: Build Docker image
          command: |
            docker build -t your-docker-username/your-image-name:latest /app

      - run:
          name: Push Docker image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push your-docker-username/your-image-name:latest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

      - build_and_push_docker:
          requires:
            - build
          filters:
            branches:
              only:
                - main
