version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8

    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13

      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt

      - run:
          name: Run tests
          command: |
            pytest

      - persist_to_workspace:
          root: .
          paths:
            - .

  build_and_push_docker:
      - run:
          name: Build Docker image
          command: |
            docker build -t harish492/test_docker:v1 .

      - run:
          name: Push Docker image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push harish492/test_docker:v1

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

      - build_and_push_docker:
          requires:
            - build
          filters:
            branches:
              only:
                - main
